---
title: "DataCamp course: R practices"
author: "Mehrnoosh"
date: "6/30/2021"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Practice 1: Creat a matrix
```{r}
# Creat star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")
               
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(titles, region))

# Creat star_wars_matrix2 as a matrix with data for the prequels trilogy
star_wars_matrix2 <- matrix(c(474.5, 552.5, 310.7, 338.7, 380.3, 468.5),
                            nrow = 3, byrow = TRUE, 
                            dimnames = list(c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith"), region))
```

## Practice 2: Adding rows/columns to a matrix
```{r}
# Combine both Star Wars trilogies in one matrix (i.e. add rows)
all_wars_matrix <- rbind(star_wars_matrix, star_wars_matrix2)

# The worldwide box office figures
worldwide_vector <- rowSums(all_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind (all_wars_matrix, worldwide_vector)

# Total revenue for US and non-US
total_revenue_vector <- colSums(all_wars_matrix)

# Bind total_revenue_vector as a row to all_wars_matrix
all_wars_matrix <- rbind (all_wars_matrix, total_revenue_vector)

# Print out all_wars_matrix
all_wars_matrix
```

## Practice 3: Selecting matrix elements
```{r}
# my_matrix[1,2] selects the element at the first row and second column.
# my_matrix[1:3,2:4] results in a matrix with the data on the rows 1, 2, 3 and columns 2, 3, 4.
# my_matrix[,1] selects all elements of the first column.
# my_matrix[1,] selects all elements of the first row.

# Select the non-US revenue for all movies
non_us_all <- all_wars_matrix[1:6, 2]

# Average non-US revenue
mean(non_us_all)

# Select the non-US revenue for first two movies
non_us_some <- non_us_all [1:2]
  
# Average non-US revenue for first two movies
mean(non_us_some)
```

## Practice 4: A little arithmetic with matrices
```{r}
# Estimate the number of visitors (in millions) for each movie in each geographical area, given a ticket costs $5.
visitors <- all_wars_matrix[1:6, 1:2]/5
visitors

# my_matrix1 * my_matrix2 creates a matrix where each element is the product of the corresponding elements in my_matrix1 and my_matrix2. This is not the standard matrix multiplication for which you should use %*% in R.
tickets_all <- c(5, 5, 6, 6, 7, 7, 4, 4, 4.5, 4.5, 4.9, 4.9)
titles_all <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi","The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")
ticket_prices_matrix <- matrix(tickets_all, nrow= 6, byrow = TRUE, dimnames = list(titles_all, region))
ticket_prices_matrix
visitors <- all_wars_matrix[1:6, 1:2]/ticket_prices_matrix
visitors

# Average number of US visitors
mean(visitors[,1])

```


## Practice 5: Factors
```{r}
# Factors are (a list of) categorical variables in R.
# Use factor() to turn vectors into factors. Type ?factor in console to learn more.

# Sex vector
sex_vector <- c("Male", "Female", "Female", "Male", "Male")

# Convert sex_vector to a factor
factor_sex_vector <- factor(sex_vector)

# Print out factor_sex_vector
factor_sex_vector
```

## Practice 6: Factors (nominal vs. ordinal categorical variables)
```{r}
# Animals: nominal
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
factor_animals_vector

# Temperature: ordinal
temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector
```
